-- 코드를 입력하세요
SELECT p.PRODUCT_CODE PRODUCT_CODE, (SUM(o.SALES_AMOUNT)*p.PRICE) SALES
FROM PRODUCT p
INNER JOIN OFFLINE_SALE o
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC