WITH m AS (SELECT MAX(FAVORITES) FAVORITES
          FROM REST_INFO
          GROUP BY FOOD_TYPE)

SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES
FROM REST_INFO a, m
WHERE m.FAVORITES = a.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY 1 DESC