-- 코드를 입력하세요
SELECT YEAR(b.SALES_DATE) YEAR, MONTH(b.SALES_DATE) MONTH, GENDER, COUNT(DISTINCT b.USER_ID) USERS
FROM USER_INFO a, ONLINE_SALE b
WHERE a.GENDER IS NOT NULL
AND a.USER_ID = b.USER_ID
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER