-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) YEAR, MONTH(o.SALES_DATE) MONTH, COUNT(DISTINCT o.user_id) PUCHASED_USERS, ROUND((COUNT(DISTINCT o.user_id) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021)), 1) PUCHASED_RATIO
FROM USER_INFO u
INNER JOIN ONLINE_SALE o
ON o.USER_ID = u.USER_ID
WHERE YEAR(u.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH